name: Check

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: npm install
        run: npm install
      - name: npm run lint
        run: npm run lint
      - name: npm run format
        run: npm run format
      - name: npm run build
        run: npm run build
